import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdirSync, writeFileSync, rmSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { initCommand } from './index.js';

function makeTempDir(): string {
  const dir = join(tmpdir(), `ralph-init-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

describe('initCommand', () => {
  let tempDir: string;
  const origCwd = process.cwd();

  beforeEach(() => {
    tempDir = makeTempDir();
    // Create a .git dir so findProjectRoot works
    mkdirSync(join(tempDir, '.git'), { recursive: true });
    process.chdir(tempDir);
  });

  afterEach(() => {
    process.chdir(origCwd);
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('creates all expected files in an empty repo', () => {
    // Add a package.json for detection
    writeFileSync(join(tempDir, 'package.json'), JSON.stringify({
      name: 'test-project',
      devDependencies: { typescript: '^5.0.0', vitest: '^1.0.0' },
    }));

    initCommand({ defaults: true });

    // Check key files exist
    expect(existsSync(join(tempDir, 'AGENTS.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'ARCHITECTURE.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/DESIGN.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/RELIABILITY.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/SECURITY.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/PLANS.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/QUALITY_SCORE.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/design-docs/index.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/design-docs/core-beliefs.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/product-specs/index.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/exec-plans/index.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/exec-plans/tech-debt-tracker.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/generated/.gitkeep'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/references/.gitkeep'))).toBe(true);
    expect(existsSync(join(tempDir, '.ralph/config.yml'))).toBe(true);
    expect(existsSync(join(tempDir, '.ralph/rules/.gitkeep'))).toBe(true);

    // Check directories exist
    expect(existsSync(join(tempDir, 'docs/exec-plans/active'))).toBe(true);
    expect(existsSync(join(tempDir, 'docs/exec-plans/completed'))).toBe(true);
  });

  it('generates AGENTS.md under 100 lines', () => {
    writeFileSync(join(tempDir, 'package.json'), JSON.stringify({
      name: 'test-project',
      devDependencies: { typescript: '^5.0.0' },
    }));

    initCommand({ defaults: true });

    const agentsMd = readFileSync(join(tempDir, 'AGENTS.md'), 'utf-8');
    const lines = agentsMd.split('\n');
    expect(lines.length).toBeLessThanOrEqual(100);
  });

  it('generates AGENTS.md with ralph-cli header comment', () => {
    writeFileSync(join(tempDir, 'package.json'), JSON.stringify({
      name: 'test-project',
      devDependencies: { typescript: '^5.0.0' },
    }));

    initCommand({ defaults: true });

    const agentsMd = readFileSync(join(tempDir, 'AGENTS.md'), 'utf-8');
    expect(agentsMd).toContain('<!-- Generated by ralph-cli. Edit freely. -->');
  });

  it('contains zero LLM provider references in generated files', () => {
    writeFileSync(join(tempDir, 'package.json'), JSON.stringify({
      name: 'test-project',
      devDependencies: { typescript: '^5.0.0' },
    }));

    initCommand({ defaults: true });

    // Check every generated file for LLM references
    const llmTerms = ['openai', 'anthropic', 'gpt-4', 'gpt-3', 'claude', 'gemini', 'chatgpt', 'context window'];
    const filesToCheck = [
      'AGENTS.md', 'ARCHITECTURE.md', 'docs/DESIGN.md', 'docs/RELIABILITY.md',
      'docs/SECURITY.md', 'docs/design-docs/core-beliefs.md',
    ];

    for (const file of filesToCheck) {
      const content = readFileSync(join(tempDir, file), 'utf-8').toLowerCase();
      for (const term of llmTerms) {
        expect(content).not.toContain(term);
      }
    }
  });

  it('does not overwrite existing files (idempotency)', () => {
    writeFileSync(join(tempDir, 'package.json'), JSON.stringify({
      name: 'test-project',
      devDependencies: { typescript: '^5.0.0' },
    }));

    // Create AGENTS.md first with custom content
    writeFileSync(join(tempDir, 'AGENTS.md'), '# My Custom AGENTS.md\n');

    initCommand({ defaults: true });

    // AGENTS.md should not be overwritten
    const content = readFileSync(join(tempDir, 'AGENTS.md'), 'utf-8');
    expect(content).toBe('# My Custom AGENTS.md\n');
  });

  it('generates valid config.yml reflecting detected project', () => {
    writeFileSync(join(tempDir, 'package.json'), JSON.stringify({
      name: 'my-app',
      dependencies: { next: '^14.0.0', react: '^18.0.0' },
      devDependencies: { typescript: '^5.0.0', vitest: '^1.0.0' },
    }));

    initCommand({ defaults: true });

    const config = readFileSync(join(tempDir, '.ralph/config.yml'), 'utf-8');
    expect(config).toContain('name: "my-app"');
    expect(config).toContain('language: typescript');
    expect(config).toContain('framework: nextjs');
    expect(config).toContain('tool: vitest');
  });

  it('core-beliefs.md contains at least 3 principles', () => {
    writeFileSync(join(tempDir, 'package.json'), JSON.stringify({
      name: 'test-project',
    }));

    initCommand({ defaults: true });

    const beliefs = readFileSync(join(tempDir, 'docs/design-docs/core-beliefs.md'), 'utf-8');
    // Count numbered principles (lines starting with number + period)
    const principles = beliefs.match(/^\d+\./gm);
    expect(principles).not.toBeNull();
    expect(principles!.length).toBeGreaterThanOrEqual(3);
  });

  it('tech-debt-tracker.md has the table template', () => {
    writeFileSync(join(tempDir, 'package.json'), JSON.stringify({
      name: 'test-project',
    }));

    initCommand({ defaults: true });

    const tracker = readFileSync(join(tempDir, 'docs/exec-plans/tech-debt-tracker.md'), 'utf-8');
    expect(tracker).toContain('| ID |');
    expect(tracker).toContain('| Description |');
    expect(tracker).toContain('Priority');
  });
});
