import type { DetectionResult } from './detect.js';

/**
 * All generated files are plain markdown. Zero references to specific LLM providers,
 * model names, or context window sizes.
 */

export function agentsMd(projectName: string, detection: DetectionResult): string {
  const buildCmd = detection.language === 'typescript' || detection.language === 'javascript'
    ? 'npm run build' : detection.language === 'python' ? 'python -m build'
    : detection.language === 'go' ? 'go build ./...' : detection.language === 'rust' ? 'cargo build' : 'make build';

  const testCmd = detection.testRunner === 'vitest' ? 'npm test'
    : detection.testRunner === 'jest' ? 'npm test'
    : detection.testRunner === 'pytest' ? 'pytest'
    : detection.testRunner === 'go-test' ? 'go test ./...'
    : detection.language === 'rust' ? 'cargo test'
    : 'npm test';

  const lintCmd = detection.linter === 'eslint' ? 'npm run lint'
    : detection.linter === 'biome' ? 'npx biome check'
    : detection.language === 'python' ? 'ruff check .'
    : detection.language === 'go' ? 'golangci-lint run'
    : detection.language === 'rust' ? 'cargo clippy'
    : 'npm run lint';

  return `<!-- Generated by ralph-cli. Edit freely. -->

# ${projectName}

## Commands

- Build: \`${buildCmd}\`
- Test: \`${testCmd}\`
- Lint: \`${lintCmd}\`

## Project Structure

- \`ARCHITECTURE.md\` — Domain map, package layering, dependency rules
- \`docs/\` — All project documentation
  - \`design-docs/\` — Design documents and core beliefs
  - \`exec-plans/\` — Execution plans and tech debt tracker
  - \`product-specs/\` — Requirement specifications
  - \`references/\` — External tool/library documentation for agents
  - \`generated/\` — Auto-generated documentation
- \`.ralph/config.yml\` — Project configuration for ralph-cli

## Documentation

| Document | Purpose |
|----------|---------|
| \`ARCHITECTURE.md\` | Domain boundaries, layers, dependency rules |
| \`docs/DESIGN.md\` | Design philosophy and patterns |
| \`docs/RELIABILITY.md\` | Reliability principles and error handling |
| \`docs/SECURITY.md\` | Security principles and data handling |
| \`docs/QUALITY_SCORE.md\` | Quality grades per domain/layer |
| \`docs/PLANS.md\` | Active and upcoming plans |
| \`docs/design-docs/core-beliefs.md\` | Core operating principles |

## References

External documentation for tools and libraries is stored in \`docs/references/\`.
Add reference docs with \`ralph ref add <url-or-path>\`.

## Operational Notes

(Updated as learnings accumulate)
`;
}

export function architectureMd(projectName: string): string {
  return `# Architecture — ${projectName}

## Domains

<!-- List your domain boundaries and their responsibilities -->

| Domain | Path | Responsibility |
|--------|------|----------------|
| <!-- e.g., auth --> | <!-- e.g., src/domain/auth --> | <!-- e.g., Authentication and authorization --> |

## Layers

Dependencies flow downward only — each layer may only import from layers above it.

1. **types** — Type definitions, interfaces, schemas
2. **config** — Configuration loading and validation
3. **data** — Data access, repositories, external API clients
4. **service** — Business logic, orchestration
5. **ui** — User interface, CLI handlers, API routes

## Cross-Cutting Concerns

<!-- Modules allowed to be imported by any layer -->

## Dependency Rules

- No circular dependencies between domains
- Each layer can only import from layers above it in the list
- Cross-cutting concerns are exempt from layer restrictions
- File size limit: 500 lines per file
`;
}

export function designMd(): string {
  return `# Design Philosophy

## Patterns

<!-- Document the design patterns and conventions used in this project -->

## Conventions

- Prefer composition over inheritance
- Keep modules focused — single responsibility
- Validate data at system boundaries
- Prefer explicit over implicit behavior
`;
}

export function reliabilityMd(): string {
  return `# Reliability

## Error Handling

- Handle errors at the appropriate level — don't swallow exceptions
- Use typed errors where the language supports it
- Fail fast on invalid state
- Log errors with enough context to debug without reproduction

## Observability

- Structured logging for machine-readable output
- Meaningful error messages for human readers

## Testing

- Test the contract, not the implementation
- Cover error paths, not just happy paths
`;
}

export function securityMd(): string {
  return `# Security

## Data Handling

- Never log secrets, tokens, or credentials
- Validate and sanitize all external input
- Use environment variables for secrets, never hardcode

## Access Control

- Principle of least privilege
- Verify authorization at every entry point

## Dependencies

- Keep dependencies minimal and audited
- Pin versions for reproducible builds
`;
}

export function coreBeliefsMd(): string {
  return `# Core Beliefs

Principles that guide how agents and developers work in this codebase.

1. **Repo is the system of record** — All architectural decisions, patterns, and conventions are documented in the repository. If it's not in the repo, it doesn't exist.

2. **Validate data at boundaries** — External input is untrusted. Validate at the edge (API handlers, CLI argument parsing, file reads), then trust internal data structures.

3. **Prefer shared utilities over hand-rolled helpers** — Before writing a helper function, check if one already exists. Duplication creates drift.

4. **Make the implicit explicit** — Configuration over convention when the convention isn't obvious. Document non-obvious decisions where they're made.

5. **Small, focused files** — Each file should have a clear, singular purpose. When a file grows beyond its scope, split it.
`;
}

export function designDocsIndexMd(): string {
  return `# Design Documents

Catalog of design documents for this project.

| Document | Status | Description |
|----------|--------|-------------|
| [core-beliefs.md](core-beliefs.md) | Active | Core operating principles |

## Adding a Design Document

Create a new markdown file in this directory. Add an entry to the table above with its status:
- **Active** — Currently followed
- **Superseded** — Replaced by a newer document
- **Draft** — Under discussion
`;
}

export function productSpecsIndexMd(): string {
  return `# Product Specifications

One topic per file. Each spec describes a single feature or concern.

| Spec | Description |
|------|-------------|

## Convention

- One spec per file — do not combine multiple features
- Use clear, descriptive filenames (e.g., \`authentication.md\`, \`billing.md\`)
- Each spec should include: Job (problem solved), Behavior (how it works), Acceptance Criteria
`;
}

export function execPlansIndexMd(): string {
  return `# Execution Plans

| ID | Title | Status | Created |
|----|-------|--------|---------|

Plans in \`active/\` are currently being worked on.
Completed or abandoned plans are moved to \`completed/\`.

See [tech-debt-tracker.md](tech-debt-tracker.md) for known technical debt.
`;
}

export function techDebtTrackerMd(): string {
  return `# Tech Debt Tracker

| ID | Description | Priority | Discovered Date | Related Plan |
|----|-------------|----------|-----------------|--------------|

## Priority Levels

- **P0** — Blocking current work or causing incidents
- **P1** — Should be addressed soon, increasing friction
- **P2** — Nice to fix, low impact
- **P3** — Cosmetic or negligible impact
`;
}

export function plansMd(): string {
  return `# Plans

Overview of active and upcoming work.

## Active Plans

<!-- Updated automatically by ralph plan commands -->

## Upcoming

<!-- Planned work not yet started -->
`;
}

export function qualityScoreMd(): string {
  return `# Quality Grades

<!-- Generated by ralph grade. Do not edit manually. -->

No quality scores generated yet. Run \`ralph grade\` to generate.
`;
}

export function configYml(projectName: string, detection: DetectionResult): string {
  let config = `project:
  name: "${projectName}"
  language: ${detection.language}`;

  if (detection.framework) {
    config += `\n  framework: ${detection.framework}`;
  }

  if (detection.testRunner && detection.testRunner !== 'none') {
    const coverageTool = detection.testRunner === 'go-test' ? 'go-test' : detection.testRunner;
    config += `\n\nquality:\n  coverage:\n    tool: ${coverageTool}`;
  }

  config += '\n';
  return config;
}
